version: '3.8'

services:
  identity-ldap-api:
    image: haitnmt/ldap-api:latest
    container_name: identity-ldap-api
    ports:
      - "8080:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_HTTPS_PORT=8080
      # Ghi đè cấu hình Redis để kết nối đến Valkey trong Docker
      - Redis__ConnectionString=valkey:6379
      - Redis__InstanceName=Api-Ldap
      - BackendUrl=https://localhost:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro
      - ./src/Haihv.Identity.Ldap.Api/appsettings.Development.json:/app/appsettings.json:ro
    depends_on:
      - valkey
    networks:
      - identity-network

  valkey:
    image: valkey/valkey:latest
    container_name: identity-valkey
    ports:
      - "6379:6379"
    networks:
      - identity-network

networks:
  identity-network:
    driver: bridge